Add pylint, testall; nothing-to-test msg to shellcheck

diff --git a/testing/pylint b/testing/pylint
--- a/testing/pylint
+++ b/testing/pylint
@@ -1,7 +1,7 @@
 #!/bin/bash 
 # shellcheck disable=1117,2219
 #
-# Finds all sh-family scripts and checks the header for a shellcheck directive.
+# Finds all Python scripts and checks the header for a pylint directive.
 # If there is one, executes shellcheck against the script and marks script as
 # passed or failed.  If there is no directive, marks the script as skipped.
 # Directives look like this:
@@ -26,7 +26,7 @@
 # so must be a valid directive.  To enable shellchecking on a script, use
 # '# shellcheck disable=' followed by the tests to disable, if any.  The
 # 'disable=' must still be present for the directive to be valid.
-shellcheck_enabled()
+pylint_enabled()
 {
   awk '
     # default to not finding directive
@@ -37,7 +37,7 @@ shellcheck_enabled()
     # find directive (do NOT check for whitespace or whole word; shellcheck
     # does not so for example "# shellchecked" will be failed out by
     # shellcheck as a bad directive
-    /^# shellcheck/ {
+    /^# pylint/ {
       rc=0
       exit
     }
@@ -58,9 +58,9 @@ shellcheck_enabled()
 # ----------------------------------------------------------------------------
 
 # check for shellcheck binary
-if ! which shellcheck >/dev/null 2>&1
+if ! which pylint >/dev/null 2>&1
 then
-  echo "Could not find shellcheck; exiting"
+  echo "Could not find pylint; exiting"
   exit
 fi
 
@@ -89,12 +89,12 @@ failed=0
 # find every (ba|k|)sh script identified by extension
 # warning for find disabled; no other way to keep state
 # shellcheck disable=2044
-for script in $(find . -type f -name \*.sh)
+for script in $(find . -type f -name \*.py -not -path ./venv/\*)
 do
   scripts[$i]=$script 
-  if shellcheck_enabled $script
+  if pylint_enabled $script
   then
-    if shellcheck "$script"
+    if pylint -rn -sn "$script"
     then  
       results[$i]="passed"
       let passed=passed+1
@@ -124,11 +124,6 @@ do
       ;;
   esac
 done
-
-if (( total == 0 ))
-then
-  echo "Found no shell scripts to check."
-fi
 
 if (( failed > 0 ))
 then
